services:
  - type: web
    name: speed-friending
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: DATABASE_URL
        value: "./data/speed-friending.sqlite"
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: "https://speed-friending.onrender.com"
      - key: REACT_APP_BACKEND_URL
        value: "https://speed-friending.onrender.com"
    buildFilter:
      paths:
      - src/**
      - public/**
      - server.js
      - database/**
      - routes/**
