services:
  - type: web
    name: speed-friending
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: DATABASE_URL
        value: "./speed-friending.sqlite"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REACT_APP_BACKEND_URL
        value: "https://speed-friending.onrender.com"
