services:
  - type: web
    name: speed-friending
    env: node
    buildCommand: npm run render-build
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: "./speed-friending.sqlite"
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: "https://speed-friending.onrender.com"
      - key: REACT_APP_BACKEND_URL
        value: "https://speed-friending.onrender.com"
